

/**
* to call a wasm function defined outside of AS from within AS, I guess
* we have declare it as an import. the function won't actually be an imported
* host function, because in gulpfile.js we splice the wat code and paste module-funcs.wat
* into the AssemblyScript output main.wat.
* then the external function will be declared twice (once as an import statement
* generated by AS, and a second time as the function def/wat code pasted in).
* so to make it valid again, gulpfile.js will find and delete the import statement
* put there by AS.
*/


bls12_g1m_toMontgomery, bls12_g1m_toMontgomery, bls12_g2m_toMontgomery, bls12_g2m_timesScalar, bls12_g1m_timesScalar, bls12_g1m_affine, bls12_g1m_neg, bls12_ftm_one, bls12_pairingEq2 

//   (func $g1m_toMontgomery (export "g1m_toMontgomery")  (param $p0 i32) (param $p1 i32)
@external("watimports", "$g1m_toMontgomery")
export declare function bls12_g1m_toMontgomery(input: i32, output: i32): void;

@external("watimports", "$g1m_fromMontgomery")
export declare function bls12_g1m_fromMontgomery(input: i32, output: i32): void;

//   (func $g2m_toMontgomery (export "g2m_toMontgomery")  (param $p0 i32) (param $p1 i32)
@external("watimports", "$g2m_toMontgomery")
export declare function bls12_g2m_toMontgomery(input: i32, output: i32): void;

@external("watimports", "$g2m_affine")
export declare function bls12_g2m_affine(input: i32, output: i32): void;

@external("watimports", "$g1m_affine")
export declare function bls12_g1m_affine(input: i32, output: i32): void;

//  (func $g1m_neg (export "g1m_neg") (type $t0) (param $p0 i32) (param $p1 i32)
@external("watimports", "$g1m_neg")
export declare function bls12_g1m_neg(input: i32, output: i32): void;

//  (func $g1m_timesScalar (export "g1m_timesScalar") (type $t8) (param $p0 i32) (param $p1 i32) (param $p2 i32) (param $p3 i32)
@external("watimports", "$g1m_timesScalar")
export declare function bls12_g1m_timesScalar(p0: i32, p1: i32, p2: i32, p3: i32): void;

@external("watimports", "$g2m_timesScalar")
export declare function bls12_g2m_timesScalar(p0: i32, p1: i32, p2: i32, p3: i32): void;


// (func $f6m_toMontgomery (export "f6m_toMontgomery") (type $t0) (param $p0 i32) (param $p1 i32)
@external("watimports", "$f6m_toMontgomery")
export declare function bls12_f6m_toMontgomery(p0: i32, p1: i32): void;

@external("watimports", "$f6m_fromMontgomery")
export declare function bls12_f6m_fromMontgomery(p0: i32, p1: i32): void;

//   (func $f6m_mul (export "f6m_mul") (type $t5) (param $p0 i32) (param $p1 i32) (param $p2 i32)
@external("watimports", "$f6m_mul")
export declare function bls12_f6m_mul(p0: i32, p1: i32, p2: i32): void;


//   (func $ftm_one (export "ftm_one") (type $t1) (param $p0 i32)
@external("watimports", "$ftm_one")
export declare function bls12_ftm_one(p0: i32): void;

//   (func $bn128_pairingEq2 (export "bn128_pairingEq2") (type $t10) (param $p0 i32) (param $p1 i32) (param $p2 i32) (param $p3 i32) (param $p4 i32) (result i32)
@external("watimports", "$bls12_pairingEq2")
export declare function bls12_pairingEq2(p0: i32, p1: i32, p2: i32, p3: i32, p4: i32): i32;
